### ISSUE TITLE
KZLinkedConsole support

### ISSUE THREAD

**Issue by kiokumicu** [goktugyil/QorumLogs#11]
Hi!
Install plugin KZLinkedConsole throw Alcatraz.
If I set QorumLogs.KZLinkedConsoleSupportEnabled = true, I got error "Type 'QorumLogs' has no member 'KZLinkedConsoleSupportEnabled"
What I'm doing wrong ?

**Comment by thellimist** [comment]
Did you download it with pods or manually? Pods is not up to date which might be the case.

**Comment by kiokumicu** [comment]
Install QorumLogs via Pods

**Comment by Esqarrouth** [comment]
Updated pods to include KZLinkedConsole, thanks for letting us know
