### ISSUE TITLE
Console output is broken

### ISSUE THREAD

**Issue by r3econ** [goktugyil/QorumLogs#17]
First I installed Alcatraz, went smoothly, then I restarted Xcode.
Then, I executed:

```
    func application(application: UIApplication, willFinishLaunchingWithOptions launchOptions: [NSObject : AnyObject]?) -> Bool {

        QorumLogs.enabled = true
        QorumLogs.test()
```

Instead nicely formatted, colorful output I'm getting this in the console:

```
 [fg120,120,120;QorumLogs.test()[91]:[; [fg0,180,180;Debug[;
 [fg120,120,120;QorumLogs.test()[92]:[; [fg0,150,0;Info[;
 [fg120,120,120;QorumLogs.test()[93]:[; [fg255,190,0;Warning[;
 [fg120,120,120;QorumLogs.test()[94]:[; [fg255,0,0;Error[;
```

**Comment by Esqarrouth** [comment]
Did you install XcodeColors correctly?

**Comment by r3econ** [comment]
Yes. I switched to using XCGLogger, this works like a charm.

**Comment by Esqarrouth** [comment]
Just tried in my running project and a new project. Its working fine. 
http://prntscr.com/aa3kd8

**Comment by Esqarrouth** [comment]
I had a problem like 3 weeks ago, not about the color but KZLinkedConsole. It somehow randomly got fixed, I obviously did the whole close the xcode, cleared derived data, restarted xcode, clean, build process. Not sure if this is the reason it got fixed or something else
