### ISSUE TITLE
Does logs work for new google forms ?

### ISSUE THREAD

**Issue by Arti3DPlayer** [goktugyil/QorumLogs#18]
I used ids from this field:
`<input type="hidden" jsname="L9xHkb" name="entry.2089538913">`

![screen shot 2016-03-08 at 21 57 18](https://cloud.githubusercontent.com/assets/3278913/13614353/be7e6342-e578-11e5-8ca3-8c7c4a13af9e.png)

```
 [fg160,32,240;OnlineLogs: [:] - v1.0(1.4) - 1Debug - QorumLogs.test()[111] - Debug[;
 [fg160,32,240;OnlineLogs: [:] - v1.0(1.4) - 2Info - QorumLogs.test()[112] - Info[;
 [fg160,32,240;OnlineLogs: [:] - v1.0(1.4) - 3Warning - QorumLogs.test()[113] - Warning[;
 [fg160,32,240;OnlineLogs: [:] - v1.0(1.4) - 4Error - QorumLogs.test()[114] - Error[;
```

```
    QorumOnlineLogs.test() 
```

is working but `QL2("Start:")` not

**Comment by Esqarrouth** [comment]
Did you try it and it is not working? Or are you asking if its working?

**Comment by Arti3DPlayer** [comment]
Oh, i figured out why it not worked. Because i call `QL2("Start")` in thread
