### ISSUE TITLE
Why import UIKit? I believe it could be ported to OS X as well

### ISSUE THREAD

**Issue by lexrus** [goktugyil/QorumLogs#2]

**Comment by Esqarrouth** [comment]
Hello, feel free to send a pull request. I don't really work on OS X apps so I might miss some other details if there are some

**Comment by Esqarrouth** [comment]
Here you go
https://github.com/goktugyil/QorumLogs/commit/e6be59331f2e4041f0cb6a741028c2793b5a181b
