### ISSUE TITLE
iOS 7.3 compatibility

### ISSUE THREAD

**Issue by staticdreams** [goktugyil/QorumLogs#20]
Is it just me or QorumLogs is not iOS 9.3 ready?
Instead of getting colourful output I get white text which looks like this: 

`[fg120,120,120;LoginViewController.swift:87 launchApplication():[; [fg0,150,0;`

I have to admit I just updated my devices and Xcode today..

**Comment by CocoaPriest** [comment]
It's the `XcodeColors` that's broken. Just follow [these steps](https://github.com/robbiehanson/XcodeColors/wiki/XcodeUpdates) to update and you'll be fine.

**Comment by staticdreams** [comment]
@CocoaPriest thanks for your help. I downloaded pre-build plugin [here](https://github.com/SwiftyBeaver/SwiftyBeaver#no-colors) and it worked.

**Comment by Esqarrouth** [comment]
Thanks
