### ISSUE TITLE
Error post cocapods installtion 

### ISSUE THREAD

**Issue by rk-kmr** [goktugyil/QorumLogs#30]
Hey, 

I have been trying to use QorumLogs for a project of mine and I installed using cocoapods(0.39.0).
After install when I try to build the project I get following errors.

![screen shot 2016-05-12 at 3 47 11 pm](https://cloud.githubusercontent.com/assets/1857610/15211489/17f1a8c2-1859-11e6-9e72-c5589f7fa186.png)

Following are the content of my cocoapods file

```
target 'MyApp' do
  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '8.0'
  use_frameworks!
  pod 'Alamofire', '~> 3.1.3'
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
  pod 'QorumLogs'
end
```

I am really sorry if its a basic issue I am new to iOS development

**Comment by Esqarrouth** [comment]
You may have added a random comma in the code somewhere?
Are the other pods working? I am using the same cocoapod version with this

```
platform :ios, '8.0'
use_frameworks!

target 'MyApp' do
pod 'QorumLogs'

end
```

**Comment by rohitash-kumar** [comment]
Sorry my bad. I was supposed to upgrade to El Captain and latest xcode.
