### ISSUE TITLE
Print logs only in Debug mode

### ISSUE THREAD

**Issue by jayesh15111988** [goktugyil/QorumLogs#42]
I am working on an application which needs to spit logs only when application is run in the debug mode and want to eliminate any logs when in release. Is it possible to customize that way. Even better, for every log I am trying to print, is it possible to specify if I want to print that log in release or not?

**Comment by Esqarrouth** [comment]
```
  QorumLogs.enabled = false
  QorumOnlineLogs.enabled = false
```
Tried this?

**Comment by jayesh15111988** [comment]
@goktugyil I will try it. Thanks for the tip!
