### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by Elshad** [goktugyil/QorumLogs#7]
There is warning about unused result of initializer

![screen shot 2015-10-21 at 10 15 45](https://cloud.githubusercontent.com/assets/2334731/10628265/c6308f98-77dc-11e5-9d5d-514eefd366a6.png)

**Comment by Esqarrouth** [comment]
Hello, fixed it here:

https://github.com/goktugyil/QorumLogs/commit/791ddf646acacdc8e5dccc268bea201ffbc108f8

Thanks
